### ISSUE TITLE
The SSH service was not successfully installed.

### ISSUE THREAD

**Issue by Srpihot** [exdial/anbernic-apps#1]
Hello, your other bash commands ran successfully, but the SSH installation script did not succeed on my RG35XX Plus. I found that the /tmp/anbernic-ssh-service.log file shows the error: "Failed to start ssh.service: Unit ssh.service not found." The system version is RG35XX+_P_V1.1.2.

**Comment by exdial** [comment]
Hey [Srpihot](https://github.com/Srpihot), thanks for pointing this bug. I updated the app. Can you reinstall app from this repo and try again?
