### ISSUE TITLE
change other settings from Chinese-specific servers

### ISSUE THREAD

**Issue by argentcorvid** [exdial/anbernic-apps#3]
Ones I have found:

NTP server is set to cn.pool.ntp.org - could just be set to pool.ntp.org

The apt repository is set to one hosted at a Chinese university. This post has some suggestions about making a new sources.list: 

https://askubuntu.com/questions/124017/how-do-i-restore-the-default-repositories

**Comment by exdial** [comment]
@argentcorvid According to the latest firmware version 1.1.5,
[RG35XXPLUS-EN-240712](https://win.anbernic.com/download/318.html) ntp server is already configured.

```bash
$ grep -i ntp /etc/systemd/timesyncd.conf
#NTP=
#FallbackNTP=ntp.ubuntu.com
```

`timesync-status` shows us
```bash
$ timedatectl timesync-status | grep -i server
Server: 185.125.190.56 (ntp.ubuntu.com)
```

As for the apt repository, it makes sense to change it. Will update soon.

**Comment by exdial** [comment]
@argentcorvid Apt's Chinese-specific settings have been changed to English. Checkout latest code.
